version: '3'
services:
  db:
    container_name: db_byx
    image: postgres:13.11-alpine3.18
    volumes:
      - /home/bruno/volumes/byx_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_HOST=${DB_HOST}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"

    restart: always
    ports:
      - "5432:5432"
    networks:
      - default
  cache:
    container_name: redis_byx
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
  web:
    build: .
    env_file:
      - ./.env
    container_name: server_byx
    entrypoint: /code/entrypoint.sh
    image: byx
    links:
      - db:db
      - cache:cache
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - db
      - cache
  worker:
    build: .
    env_file:
      - ./.env
    container_name: celery_worker
    command: celery -A desafio_byx worker --loglevel=info
    volumes:
      - .:/code
    links:
      - cache
    depends_on:
      - cache
      - db
      - web
    networks:
      - default
  beat:
    build: .
    env_file:
      - ./.env
    container_name: celery_beat
    command: celery -A desafio_byx beat -l info
    volumes:
      - .:/code
    links:
      - worker
      - cache
      - db
    depends_on:
      - worker
      - cache
    networks:
      - default
