# Generated by Django 4.2.3 on 2023-07-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.BigIntegerField(unique=True, verbose_name="Code")),
                ("barcode", models.CharField(max_length=200, verbose_name="Barcode")),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                ("url", models.CharField(max_length=200, verbose_name="Url")),
                ("quantity", models.CharField(max_length=50, verbose_name="Barcode")),
                (
                    "categories",
                    models.CharField(max_length=100, verbose_name="Categories"),
                ),
                (
                    "packaging",
                    models.CharField(max_length=100, verbose_name="Packaging"),
                ),
                ("brands", models.CharField(max_length=100, verbose_name="Brands")),
                ("image_url", models.CharField(max_length=250, verbose_name="Image")),
                (
                    "imported_t",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Imported"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("IMPORTED", "Imported")],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-pk"],
            },
        ),
    ]
