# Generated by Django 4.2.3 on 2023-07-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brands",
            field=models.CharField(max_length=200, verbose_name="Brands"),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.CharField(max_length=200, verbose_name="Categories"),
        ),
        migrations.AlterField(
            model_name="product",
            name="packaging",
            field=models.CharField(max_length=200, verbose_name="Packaging"),
        ),
    ]
